sample_user_einfra_id: fca9cd0c7d898d8a0c86d445d15ba974296ff989@einfra.cesnet.cz
sample_user_id: "14081"
sample_user_first_name: Miroslav
sample_user_last_name: Bauer
sample_user_uuid: 326598bc-be08-4b00-8dc7-0e3e0d4cbafa

member_by_user_id: "170416"
member_by_user_created_by: danecek@cesnet.cz
member_by_user_created_by_id: "54563"

attribute_created_by: 445753@muni.cz

nrp_fa_devrepo_service: df6fe45d8bb8eabb942792eacc62f57df2e2a5e1@einfra.cesnet.cz
# keep devrepo id unchanged, because otherwise we would need to change the API
# nrp_fa_devrepo_id: 143975
nrp_fa_devrepo_uuid: 32db7ec4-f207-479d-a5c9-ef3ecad568a5
nrp_fa_creator_id: 59835
